### ISSUE TITLE
Increase table-of-contents depth

### ISSUE THREAD

**Issue by matt-dray** [The-Strategy-Unit/nhp_peers_params#49]
The qmd in #44 has `toc-depth: 3` in the YAML, but it isn't enacted in the output (it's only a depth of 1). This makes it hard to navigate. 

First, I think the toc declarations should be nested under `format` in the YAML like:

```
format: 
  html:
    page-layout: full
    fig-width: 9.5
    fig-height: 6.5
    self-contained: true
    toc: true
    toc-depth: 3
    toc-expand: false
    number-sections: true
    number-offset: 0
```

Second, I was expecting that the TOC levels would expand in the sidebar when I scrolled to a section, but that didn't happen. Of course, changing `toc-expand` to `true` meant I could see all the sections; I suggest you do this in the interim if you can't solve it.
